// @flow

const SET_LIST_PEOPLE = 'SET_LIST_PEOPLE';
export const ADD_LIST_PEOPLE = 'ADD_LIST_PEOPLE';
export const EDIT_LIST_PEOPLE = 'EDIT_LIST_PEOPLE';
export const SET_EDIT_PROFILE = 'SET_EDIT_PROFILE';

export default SET_LIST_PEOPLE;
